require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsermailsController do

  # This should return the minimal set of attributes required to create a valid
  # Usermail. As you add validations to Usermail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all usermails as @usermails" do
      usermail = Usermail.create! valid_attributes
      get :index
      assigns(:usermails).should eq([usermail])
    end
  end

  describe "GET show" do
    it "assigns the requested usermail as @usermail" do
      usermail = Usermail.create! valid_attributes
      get :show, :id => usermail.id.to_s
      assigns(:usermail).should eq(usermail)
    end
  end

  describe "GET new" do
    it "assigns a new usermail as @usermail" do
      get :new
      assigns(:usermail).should be_a_new(Usermail)
    end
  end

  describe "GET edit" do
    it "assigns the requested usermail as @usermail" do
      usermail = Usermail.create! valid_attributes
      get :edit, :id => usermail.id.to_s
      assigns(:usermail).should eq(usermail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Usermail" do
        expect {
          post :create, :usermail => valid_attributes
        }.to change(Usermail, :count).by(1)
      end

      it "assigns a newly created usermail as @usermail" do
        post :create, :usermail => valid_attributes
        assigns(:usermail).should be_a(Usermail)
        assigns(:usermail).should be_persisted
      end

      it "redirects to the created usermail" do
        post :create, :usermail => valid_attributes
        response.should redirect_to(Usermail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved usermail as @usermail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Usermail.any_instance.stub(:save).and_return(false)
        post :create, :usermail => {}
        assigns(:usermail).should be_a_new(Usermail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Usermail.any_instance.stub(:save).and_return(false)
        post :create, :usermail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested usermail" do
        usermail = Usermail.create! valid_attributes
        # Assuming there are no other usermails in the database, this
        # specifies that the Usermail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Usermail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => usermail.id, :usermail => {'these' => 'params'}
      end

      it "assigns the requested usermail as @usermail" do
        usermail = Usermail.create! valid_attributes
        put :update, :id => usermail.id, :usermail => valid_attributes
        assigns(:usermail).should eq(usermail)
      end

      it "redirects to the usermail" do
        usermail = Usermail.create! valid_attributes
        put :update, :id => usermail.id, :usermail => valid_attributes
        response.should redirect_to(usermail)
      end
    end

    describe "with invalid params" do
      it "assigns the usermail as @usermail" do
        usermail = Usermail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Usermail.any_instance.stub(:save).and_return(false)
        put :update, :id => usermail.id.to_s, :usermail => {}
        assigns(:usermail).should eq(usermail)
      end

      it "re-renders the 'edit' template" do
        usermail = Usermail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Usermail.any_instance.stub(:save).and_return(false)
        put :update, :id => usermail.id.to_s, :usermail => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested usermail" do
      usermail = Usermail.create! valid_attributes
      expect {
        delete :destroy, :id => usermail.id.to_s
      }.to change(Usermail, :count).by(-1)
    end

    it "redirects to the usermails list" do
      usermail = Usermail.create! valid_attributes
      delete :destroy, :id => usermail.id.to_s
      response.should redirect_to(usermails_url)
    end
  end

end
